name: lint
on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - 'aqua.yaml'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - 'aqua.yaml'
      - '.github/workflows/lint.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with: { go-version-file: go.mod }
      - name: go mod verify
        run: go mod verify
      - name: go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with: { version: v2.11.4 }
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with: { aqua_version: v2.59.1 }
      - name: govulncheck
        run: govulncheck ./...
