name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version-file: go.mod }
      - name: go mod verify
        run: go mod verify
      - name: go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      - uses: golangci/golangci-lint-action@v6
        with: { version: v2.11.4 }
      - uses: aquaproj/aqua-installer@v4.0.4
      - name: govulncheck
        run: govulncheck ./...
